apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eucloud-ingress
  namespace: eucloud
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
  - host: 192.168.124.50
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: eucloud-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eucloud-frontend
            port:
              number: 80
